<?php
declare(strict_types=1);

namespace BcWpExport\Service;

use DOMDocument;
use DOMElement;

class WxrWriterService
{
    public function buildEmptyDocument(): string
    {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rss version=\"2.0\"></rss>\n";
    }

    public function buildDocument(array $context = []): string
    {
        $document = new DOMDocument('1.0', 'UTF-8');
        $document->formatOutput = !empty($context['pretty_print']);

        $rss = $document->createElement('rss');
        $rss->setAttribute('version', '2.0');
        // setAttributeNS で xmlns 名前空間に正しく登録することで、
        // createElementNS で生成した子要素が各自で xmlns: を再宣言しなくなる
        $xmlnsNs = 'http://www.w3.org/2000/xmlns/';
        $rss->setAttributeNS($xmlnsNs, 'xmlns:excerpt', 'http://wordpress.org/export/1.2/excerpt/');
        $rss->setAttributeNS($xmlnsNs, 'xmlns:content', 'http://purl.org/rss/1.0/modules/content/');
        $rss->setAttributeNS($xmlnsNs, 'xmlns:wfw',     'http://wellformedweb.org/CommentAPI/');
        $rss->setAttributeNS($xmlnsNs, 'xmlns:dc',      'http://purl.org/dc/elements/1.1/');
        $rss->setAttributeNS($xmlnsNs, 'xmlns:wp',      'http://wordpress.org/export/1.2/');
        $document->appendChild($rss);

        $channel = $document->createElement('channel');
        $rss->appendChild($channel);
        $channelTitleEl = $document->createElement('title');
        $channelTitleEl->appendChild($document->createTextNode((string) ($context['channel_title'] ?? 'baserCMS Export')));
        $channel->appendChild($channelTitleEl);
        $channel->appendChild($document->createElement('language', (string) ($context['language'] ?? 'ja')));
        $channel->appendChild($document->createElement('wp:wxr_version', '1.2'));
        $channel->appendChild($document->createElement('generator', 'BcWpExport'));

        if (!empty($context['include_site_meta'])) {
            $channel->appendChild($document->createElement('description', 'Generated by BcWpExport'));
        }

        if (!empty($context['summary']) && is_array($context['summary'])) {
            foreach ($context['summary'] as $key => $value) {
                if (!is_scalar($value)) {
                    continue;
                }
                $channel->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:' . $key, (string) $value));
            }
        }

        foreach ($context['authors'] ?? [] as $author) {
            $authorNode = $document->createElementNS('http://wordpress.org/export/1.2/', 'wp:author');
            $this->appendCdataElement($document, $authorNode, 'wp:author_login', 'http://wordpress.org/export/1.2/', (string) ($author['login'] ?? ''));
            $this->appendCdataElement($document, $authorNode, 'wp:author_email', 'http://wordpress.org/export/1.2/', (string) ($author['email'] ?? ''));
            $this->appendCdataElement($document, $authorNode, 'wp:author_display_name', 'http://wordpress.org/export/1.2/', (string) ($author['display_name'] ?? ''));
            $channel->appendChild($authorNode);
        }

        foreach ($context['items'] ?? [] as $item) {
            $itemNode = $document->createElement('item');
            $itemTitleEl = $document->createElement('title');
            $itemTitleEl->appendChild($document->createTextNode((string) ($item['title'] ?? '')));
            $itemNode->appendChild($itemTitleEl);
            $itemNode->appendChild($document->createElement('pubDate', date(DATE_RSS, strtotime((string) ($item['post_date'] ?? 'now')))));
            $this->appendCdataElement($document, $itemNode, 'dc:creator', 'http://purl.org/dc/elements/1.1/', (string) ($item['creator'] ?? ''));
            $this->appendCdataElement($document, $itemNode, 'content:encoded', 'http://purl.org/rss/1.0/modules/content/', (string) ($item['content'] ?? ''));
            $this->appendCdataElement($document, $itemNode, 'excerpt:encoded', 'http://wordpress.org/export/1.2/excerpt/', (string) ($item['excerpt'] ?? ''));
            $itemNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:post_date', (string) ($item['post_date'] ?? '')));
            $itemNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:post_date_gmt', (string) ($item['post_date_gmt'] ?? '')));
            $itemNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:post_name', (string) ($item['post_name'] ?? '')));
            $itemNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:status', (string) ($item['post_status'] ?? 'publish')));
            $itemNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:post_type', (string) ($item['post_type'] ?? 'post')));
            $itemNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:post_id', (string) ($item['wp_post_id'] ?? 0)));
            $itemNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:post_parent', (string) ($item['wp_post_parent'] ?? 0)));

            // attachment アイテムの場合は wp:attachment_url を出力する
            if (!empty($item['attachment_url'])) {
                $itemNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:attachment_url', (string) $item['attachment_url']));
            }

            // postmeta（例: _thumbnail_id）を出力する
            foreach ($item['postmeta'] ?? [] as $meta) {
                $metaNode = $document->createElementNS('http://wordpress.org/export/1.2/', 'wp:postmeta');
                $metaNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:meta_key', (string) ($meta['key'] ?? '')));
                $metaNode->appendChild($document->createElementNS('http://wordpress.org/export/1.2/', 'wp:meta_value', (string) ($meta['value'] ?? '')));
                $itemNode->appendChild($metaNode);
            }

            foreach ($item['categories'] ?? [] as $category) {
                $categoryNode = $document->createElement('category');
                $categoryNode->setAttribute('domain', 'category');
                $categoryNode->setAttribute('nicename', (string) ($category['slug'] ?? ''));
                $categoryNode->appendChild($document->createCDATASection((string) ($category['label'] ?? '')));
                $itemNode->appendChild($categoryNode);
            }

            foreach ($item['tags'] ?? [] as $tag) {
                $tagNode = $document->createElement('category');
                $tagNode->setAttribute('domain', 'post_tag');
                $tagNode->setAttribute('nicename', (string) ($tag['slug'] ?? ''));
                $tagNode->appendChild($document->createCDATASection((string) ($tag['label'] ?? '')));
                $itemNode->appendChild($tagNode);
            }

            $channel->appendChild($itemNode);
        }

        return $document->saveXML() ?: $this->buildEmptyDocument();
    }

    protected function appendCdataElement(DOMDocument $document, DOMElement $parent, string $qualifiedName, string $namespaceUri, string $value): void
    {
        $element = $document->createElementNS($namespaceUri, $qualifiedName);
        $element->appendChild($document->createCDATASection($value));
        $parent->appendChild($element);
    }
}
